# Generated by Django 5.1.1 on 2024-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('location_of_shoot', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_address', models.TextField()),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Baby Birthday', 'Baby Birthday'), ('Model Shoot', 'Model Shoot'), ('Nikah Photography', 'Nikah Photography'), ('Engagement', 'Engagement'), ('Portrait', 'Portrait')], max_length=20)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
                'ordering': ['-id'],
            },
        ),
    ]
