# Generated by Django 5.1.1 on 2024-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_number', models.BigIntegerField()),
                ('location_of_shoot', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_address_details', models.TextField()),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Baby Birthday', 'Baby Birthday'), ('Model Shoot', 'Model Shoot'), ('Nikah Photography', 'Nikah Photography'), ('Engagement', 'Engagement'), ('Portrait', 'Portrait')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='wedding_photos')),
                ('videolink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GelleryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='portfolio_images')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingPhotography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_photos')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='event_address',
            new_name='event_address_details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Baby Birthday', 'Baby Birthday'), ('Model Shoot', 'Model Shoot'), ('Nikah Photography', 'Nikah Photography'), ('Engagement', 'Engagement'), ('Portrait', 'Portrait')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
